Controller:
  type: PID
  file: controllers/3dofPID.yaml

Dynamics:
  type: linear
  file: dynamics/simple.yaml

ControlSystem:
  rate: 10 # Hz
  safetyFilterEnabled: true

SafetyFilter:
  type: qp
  file: safety/qpsf.yaml
